#!/usr/bin/env bash

if [ "$TRAVIS_TAG" != "" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    echo "Building docker image $DOCKER_REPO:$TRAVIS_TAG"
    docker login -u $DOCKER_USER -p $DOCKER_PASS

    npm run-script docker-publish
fi

